title: The Programming Squirrel
description: "Welcome to my development content creator blog, 'The Programming Squirrel,' a platform for in-depth coding tutorials."
permalink: /:slugified_categories/:title/

date_format: "%b %-d, %Y"

exclude:
  - "package*.json"
  - "*.config.js"
  - netlify.toml
  - README.md
  - LICENSE
  - Makefile
